{"uuid":"51914fed-ba9a-4d1f-a014-b7bf565f0ae3","historyId":"daf5885c172b30a0b031191d879bf7a4","fullName":"com.qacart.shaft.Api.sendRequest","labels":[{"name":"package","value":"com.qacart.shaft.Api"},{"name":"testClass","value":"com.qacart.shaft.Api"},{"name":"testMethod","value":"sendRequest"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":"shaft-demo"},{"name":"subSuite","value":"com.qacart.shaft.Api"},{"name":"host","value":"TDV-HQ-L21"},{"name":"thread","value":"14268@TDV-HQ-L21.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"sendRequest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Perform request failed \"https://todo.qacart.com/api/v1/users/login, Response Time: 1791ms\". Root cause: \"java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\"","trace":"java.lang.AssertionError: Perform request failed \"https://todo.qacart.com/api/v1/users/login, Response Time: 1791ms\". Root cause: \"java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\"\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat com.shaft.tools.io.internal.FailureReporter.fail(FailureReporter.java:34)\r\n\tat com.shaft.api.RestActions.failAction(RestActions.java:100)\r\n\tat com.shaft.api.RestActions.failAction(RestActions.java:459)\r\n\tat com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:303)\r\n\tat com.shaft.api.RequestBuilder.perform(RequestBuilder.java:264)\r\n\tat com.qacart.shaft.Api.sendRequest(Api.java:18)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\r\n\tat com.shaft.api.RestActions.failAction(RestActions.java:100)\r\n\tat com.shaft.api.RestActions.failAction(RestActions.java:459)\r\n\tat com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:299)\r\n\t... 27 more\r\n"},"stage":"finished","steps":[{"name":"Assertion Failed: Evaluating that the response is successful (Status code is between 200 and 299)...","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"Validation Test Data - Failure Reason","source":"ca66c174-33d2-4f7d-8c27-43e66a867fc6-attachment"}],"parameters":[{"name":"customLog","value":"Assertion Failed: Evaluating that the response is successful (Status code is between 200 and 299)..."},{"name":"attachments","value":"[[Validation Test Data, Failure Reason, java.lang.AssertionError: Assertion \"ValidateEquals\" FAILED. Expected \"true\" and Actual \"false\". Comparison Type \"EQUALS\". Validation Type \"POSITIVE\".\r\n com.shaft.validation.internal.ValidationsHelper.reportValidationState(ValidationsHelper.java:639)\r\n com.shaft.validation.internal.ValidationsHelper.fail(ValidationsHelper.java:395)\r\n com.shaft.validation.internal.ValidationsHelper.validateEquals(ValidationsHelper.java:70)\r\n com.shaft.validation.internal.ValidationsExecutor.perform(ValidationsExecutor.java:144)\r\n com.shaft.api.RestActions.evaluateResponseStatusCode(RestActions.java:1223)\r\n com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:293)\r\n com.shaft.api.RequestBuilder.perform(RequestBuilder.java:264)\r\n com.qacart.shaft.Api.sendRequest(Api.java:18)\r\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n org.testng.TestRunner.run(TestRunner.java:621)\r\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n org.testng.TestNG.runSuites(TestNG.java:1114)\r\n org.testng.TestNG.run(TestNG.java:1082)\r\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n]]"}],"start":1688933301897,"stop":1688933301904},{"name":"Assertion \"ValidateEquals\" FAILED. Expected \"true\" and Actual \"false\". Comparison Type \"EQUALS\". Validation Type \"POSITIVE\".","status":"failed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1688933301907,"stop":1688933301907},{"name":"Perform request failed \"POST | Target Status Code: 0 | Service URL: https://todo.qacart.com/api/v1/users/login | Content Type: application/json | Response Time: 1791ms\".","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false,"trace":"Headers:\r\n_______________\r\n\r\nContent-Type=application/json\r\njava.io.ByteArrayInputStream@18f7a872\r\njava.io.ByteArrayInputStream@61defefb"},"stage":"finished","steps":[],"attachments":[{"name":"API Request - Specifications","source":"d2c6aaea-41af-4b1f-b16b-1a340fe64288-attachment"},{"name":"API Request - JSON Body","source":"a070dddc-aea7-4108-8db3-f980d69f72b9-attachment.json","type":"text/json"},{"name":"API Response - JSON Body","source":"e5627292-f90e-455a-bbaf-1c87a9cea02b-attachment.json","type":"text/json"}],"parameters":[{"name":"logText","value":"Perform request failed \"POST | Target Status Code: 0 | Service URL: https://todo.qacart.com/api/v1/users/login | Content Type: application/json | Response Time: 1791ms\"."},{"name":"attachments","value":"[[API Request, Specifications, Headers:\r\n_______________\r\n\r\nContent-Type=application/json\r\n\r\n], [API Request, JSON Body, java.io.ByteArrayInputStream@18f7a872], null, [API Response, JSON Body, java.io.ByteArrayInputStream@61defefb]]"},{"name":"status","value":"FAIL"}],"start":1688933302760,"stop":1688933303056},{"name":"Perform request failed \"https://todo.qacart.com/api/v1/users/login, Response Time: 1791ms\".","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false,"trace":"Headers:\r\n_______________\r\n\r\nContent-Type=application/json\r\njava.io.ByteArrayInputStream@3a24306e\r\njava.io.ByteArrayInputStream@6b127d96\r\njava.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\r\n com.shaft.api.RestActions.failAction(RestActions.java:100)\r\n com.shaft.api.RestActions.failAction(RestActions.java:459)\r\n com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:299)\r\n com.shaft.api.RequestBuilder.perform(RequestBuilder.java:264)\r\n com.qacart.shaft.Api.sendRequest(Api.java:18)\r\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n org.testng.TestRunner.run(TestRunner.java:621)\r\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n org.testng.TestNG.runSuites(TestNG.java:1114)\r\n org.testng.TestNG.run(TestNG.java:1082)\r\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)"},"stage":"finished","steps":[],"attachments":[{"name":"API Request - Specifications","source":"200639bd-d39c-4174-a200-868961bd6879-attachment"},{"name":"API Request - JSON Body","source":"44c291e7-2e29-469a-8bae-746deca4a3e1-attachment.json","type":"text/json"},{"name":"API Response - JSON Body","source":"b3fb1802-f5d6-4bb3-95ce-2a806c3c7b99-attachment.json","type":"text/json"},{"name":"API Action Exception - Perform request - Stacktrace","source":"190f72eb-eed3-46c1-a3d3-ff8a375bb467-attachment"}],"parameters":[{"name":"logText","value":"Perform request failed \"https://todo.qacart.com/api/v1/users/login, Response Time: 1791ms\"."},{"name":"attachments","value":"[[API Request, Specifications, Headers:\r\n_______________\r\n\r\nContent-Type=application/json\r\n\r\n], [API Request, JSON Body, java.io.ByteArrayInputStream@3a24306e], null, [API Response, JSON Body, java.io.ByteArrayInputStream@6b127d96], [API Action Exception - Perform request, Stacktrace, java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\r\n com.shaft.api.RestActions.failAction(RestActions.java:100)\r\n com.shaft.api.RestActions.failAction(RestActions.java:459)\r\n com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:299)\r\n com.shaft.api.RequestBuilder.perform(RequestBuilder.java:264)\r\n com.qacart.shaft.Api.sendRequest(Api.java:18)\r\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n org.testng.TestRunner.run(TestRunner.java:621)\r\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n org.testng.TestNG.runSuites(TestNG.java:1114)\r\n org.testng.TestNG.run(TestNG.java:1082)\r\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n]]"},{"name":"status","value":"FAIL"}],"start":1688933303058,"stop":1688933303069},{"name":"Perform request failed \"https://todo.qacart.com/api/v1/users/login, Response Time: 1791ms\". Root cause: \"java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\"","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false,"trace":"java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\r\n com.shaft.api.RestActions.failAction(RestActions.java:100)\r\n com.shaft.api.RestActions.failAction(RestActions.java:459)\r\n com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:299)\r\n com.shaft.api.RequestBuilder.perform(RequestBuilder.java:264)\r\n com.qacart.shaft.Api.sendRequest(Api.java:18)\r\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n org.testng.TestRunner.run(TestRunner.java:621)\r\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n org.testng.TestNG.runSuites(TestNG.java:1114)\r\n org.testng.TestNG.run(TestNG.java:1082)\r\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)"},"stage":"finished","steps":[],"attachments":[{"name":"Rest actions - Get  stack  trace - Exception Stacktrace","source":"f7974d35-f71e-41b9-9870-1187222fa97e-attachment"}],"parameters":[{"name":"logText","value":"Perform request failed \"https://todo.qacart.com/api/v1/users/login, Response Time: 1791ms\". Root cause: \"java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\""},{"name":"attachments","value":"[[Rest actions - Get  stack  trace, Exception Stacktrace, java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\r\n com.shaft.api.RestActions.failAction(RestActions.java:100)\r\n com.shaft.api.RestActions.failAction(RestActions.java:459)\r\n com.shaft.api.RequestBuilder.performRequest(RequestBuilder.java:299)\r\n com.shaft.api.RequestBuilder.perform(RequestBuilder.java:264)\r\n com.qacart.shaft.Api.sendRequest(Api.java:18)\r\n java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n org.testng.TestRunner.run(TestRunner.java:621)\r\n org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n org.testng.TestNG.runSuites(TestNG.java:1114)\r\n org.testng.TestNG.run(TestNG.java:1082)\r\n com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n]]"},{"name":"status","value":"FAIL"}],"start":1688933303079,"stop":1688933303082}],"attachments":[{"name":"SHAFT Engine Logs - Current Method log: sendRequest","source":"59366116-0430-40df-b46e-a7222a2f385e-attachment.txt","type":"text/plain"}],"parameters":[],"start":1688933297831,"stop":1688933303104}